import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export async function POST() {
  // Create clubs
  const clubs = await Promise.all([
    prisma.club.upsert({ where: { name: "הפועל ראשון לציון" }, update: {}, create: { name: "הפועל ראשון לציון", region: "ראשון לציון", tier: "target", isTargetClub: true } }),
    prisma.club.upsert({ where: { name: "עירוני קרית גת" }, update: {}, create: { name: "עירוני קרית גת", region: "קרית גת", tier: "target", isTargetClub: true } }),
    prisma.club.upsert({ where: { name: "עירוני בית שמש" }, update: {}, create: { name: "עירוני בית שמש", region: "בית שמש", tier: "target", isTargetClub: true } }),
    prisma.club.upsert({ where: { name: "עירוני מודיעין" }, update: {}, create: { name: "עירוני מודיעין", region: "מודיעין", tier: "target", isTargetClub: true } }),
    prisma.club.upsert({ where: { name: "הפועל פתח תקווה" }, update: {}, create: { name: "הפועל פתח תקווה", region: "פתח תקווה", tier: "target", isTargetClub: true } }),
    prisma.club.upsert({ where: { name: "מכבי תל אביב" }, update: {}, create: { name: "מכבי תל אביב", region: "תל אביב", tier: "top", isTopClub: true } }),
    prisma.club.upsert({ where: { name: "מכבי חיפה" }, update: {}, create: { name: "מכבי חיפה", region: "חיפה", tier: "top", isTopClub: true } }),
    prisma.club.upsert({ where: { name: "הפועל תל אביב" }, update: {}, create: { name: "הפועל תל אביב", region: "תל אביב", tier: "top", isTopClub: true } }),
  ]);

  const [rishon, kiryatGat, beitShemesh, modiin, petahTikva, mta] = clubs;

  // Seed players
  const players = [
    {
      fullName: "שחקן לדוגמה - דני כהן",
      birthYear: 2008,
      position: "בלם",
      region: "ראשון לציון",
      currentClubId: rishon.id,
      previousClubs: JSON.stringify(["מכבי תל אביב"]),
      formerTopClub: true,
      topClubName: "מכבי תל אביב",
      appearances: 22,
      starts: 20,
      minutes: 1750,
      goals: 1,
      assists: 2,
      assistsVerified: true,
      yellowCards: 3,
      redCards: 0,
      realism: "High",
      verificationStatus: "מאומת חלקית",
      isExampleData: true,
      filterTriggered: "מודל 3 - רקע מועדון גדול, הזדמנות במועדון קטן",
      whyInteresting: "בלם 2008 שעלה מאקדמיית מכבי ת\"א להפועל ראשל\"צ. 22 הופעות, 20 הרכבים. שחקן אחראי שמשחק משחקים מלאים.",
      nextAction: "לצפות ב-10 דקות ראשונות ואחרונות מול קבוצת טופ 5",
    },
    {
      fullName: "שחקן לדוגמה - עומר לוי",
      birthYear: 2009,
      position: "חלוץ",
      region: "קרית גת",
      currentClubId: kiryatGat.id,
      playsAboveAge: true,
      appearances: 16,
      starts: 12,
      minutes: 980,
      goals: 11,
      assists: null,
      assistsVerified: false,
      yellowCards: 1,
      redCards: 0,
      realism: "High",
      verificationStatus: "דרוש וידאו",
      isExampleData: true,
      filterTriggered: "חלוץ 2009 שמשחק מעל גיל",
      whyInteresting: "חלוץ 2009 שמשחק ב-U19. 11 שערים ב-16 הופעות. דרוש אימות שהוא באמת משחק מעל גילו ולא רק ב-U17.",
      nextAction: "אימות דרך גיליון משחק שהוא משחק ב-U19",
    },
    {
      fullName: "שחקן לדוגמה - איתי מזרחי",
      birthYear: 2008,
      position: "כנף ימני",
      region: "בית שמש",
      currentClubId: beitShemesh.id,
      appearances: 24,
      starts: 22,
      minutes: 1890,
      goals: 14,
      assists: 7,
      assistsVerified: true,
      yellowCards: 2,
      redCards: 0,
      realism: "High",
      verificationStatus: "מאומת חלקית",
      isExampleData: true,
      filterTriggered: "מודל 1 - שחקן אחראי במועדון לא-טופ",
      whyInteresting: "כנף 2008 עם 14 שערים ו-7 בישולים ב-24 הופעות. שחקן דומיננטי בבית שמש. התאמה גיאוגרפית מצוינת.",
      nextAction: "לצפות במשחק מלא מול קבוצה חזקה",
    },
    {
      fullName: "שחקן לדוגמה - יואב אברהם",
      birthYear: 2008,
      position: "קשר מרכזי",
      region: "מודיעין",
      currentClubId: modiin.id,
      stuckInU19: true,
      lateBloomer: true,
      appearances: 20,
      starts: 8,
      minutes: 680,
      goals: 3,
      assists: null,
      assistsVerified: false,
      yellowCards: 4,
      redCards: 0,
      realism: "Medium",
      verificationStatus: "דרוש גיליון משחק",
      isExampleData: true,
      filterTriggered: "מודל 2 - חזק ב-U17, תקוע במעבר ל-U19",
      whyInteresting: "קשר 2008 שהיה מוביל ב-U17 אבל מקבל מעט דקות ב-U19. 8 הרכבים מתוך 20. נכנס הרבה אחרי דקה 70. פורח מאוחר פוטנציאלי.",
      nextAction: "לבדוק גיליון משחק - כמה פעמים נכנס מהספסל ומתי",
    },
    {
      fullName: "שחקן לדוגמה - אורי שפירא",
      birthYear: 2009,
      position: "שוער",
      region: "פתח תקווה",
      currentClubId: petahTikva.id,
      previousClubs: JSON.stringify(["מכבי חיפה"]),
      formerTopClub: true,
      topClubName: "מכבי חיפה",
      playsAboveAge: true,
      appearances: 14,
      starts: 14,
      minutes: 1260,
      goals: 0,
      yellowCards: 0,
      redCards: 0,
      realism: "Medium",
      verificationStatus: "דרוש וידאו",
      isExampleData: true,
      filterTriggered: "מודל 3 - שוער 2009 מאקדמיית מכבי חיפה",
      whyInteresting: "שוער 2009 שעלה ממכבי חיפה להפועל פ\"ת. משחק מעל גילו ב-U19. 14 הופעות, כולן בהרכב. דרוש וידאו לבדיקת רמה.",
      nextAction: "לצפות בוידאו - 10 דקות ראשונות ואחרונות",
    },
  ];

  for (const p of players) {
    await prisma.player.create({ data: p });
  }

  // Create interesting matches
  await prisma.match.createMany({
    data: [
      {
        homeTeamName: "עירוני בית שמש",
        awayTeamName: "מכבי תל אביב",
        league: "ליגת הנוער",
        ageGroup: "U19",
        date: "2026-03-15",
        result: "1:1",
        round: "18",
        isInterestingForScouting: true,
        scoutingReason: "תיקו של קבוצה קטנה מול מכבי ת\"א. ביצוע הגנתי משמעותי.",
        recommendedTeamToWatch: "עירוני בית שמש",
        recommendedPositions: "בלם, מגן ימני, קשר הגנתי",
      },
      {
        homeTeamName: "הפועל ראשון לציון",
        awayTeamName: "מכבי חיפה",
        league: "ליגת הנוער",
        ageGroup: "U19",
        date: "2026-02-22",
        result: "2:1",
        round: "15",
        isInterestingForScouting: true,
        scoutingReason: "ניצחון של קבוצה קטנה על מכבי חיפה. לבדוק שחקנים שלקחו אחריות.",
        recommendedTeamToWatch: "הפועל ראשון לציון",
        recommendedPositions: "חלוץ, כנף, קשר מרכזי",
      },
      {
        homeTeamName: "עירוני קרית גת",
        awayTeamName: "הפועל תל אביב",
        league: "ליגת הנוער",
        ageGroup: "U19",
        date: "2026-04-05",
        result: "0:1",
        round: "20",
        isInterestingForScouting: true,
        scoutingReason: "הפסד צמוד של קרית גת מול הפועל ת\"א. ביצוע הגנתי תחת לחץ.",
        recommendedTeamToWatch: "עירוני קרית גת",
        recommendedPositions: "בלם, שוער, קשר הגנתי",
      },
    ],
  });

  return NextResponse.json({ message: "נתוני דוגמה נוצרו בהצלחה" });
}
